# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink: pretty

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
paginate: 10
paginate_path: "/page:num"

# Setup
title:            Michelangelo Accettura III
tagline:          'A developer blog'
description:      'Detroit based .NET Developer.'
baseurl:          /
tag_page:         'tags/'
disqus_shortname: michelangeloaccettura-com
excerpt_separator: <!--more-->
#dev
#disqus_shortname: dev-michelangeloaccettura-com

# Usernames
github_username: 'maccettura'
linkedin_username: 'maccettura'
twitter_username: 'michelangeloIII'

# Links
stackoverflow_link: 'https://stackoverflow.com/users/2457029/maccettura'
  
# Custom vars
version:          2.1.0


