# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
paginate: 5
paginate_path: "page:num"

#relative_permalinks: true

# Setup
title:            Michelangelo Accettura III
tagline:          'A developer blog'
description:      'Detroit based .NET Developer.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Michelangelo Accettura III'
  url:            https://twitter.com/maccettura


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/maccettura
